# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e24023f5dcbf11d8e972f942983cba1ef7511b848afe03cb80de31e0965ab4fe2cb562529de758c83e34931005b28194ba34a08a1644fc4f16ebc134057d79f5

test:
  secret_key_base: 1a40a6c8d677d39237ea5f43aeeef09f21dfea847946f72312db0fe4d44ce1e639ac6185bd47c6472e6409b01114b92d194b6f40cf51058d423a164828300e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
